### ISSUE TITLE
How to test command redis 'SetArgs'

### ISSUE THREAD

**Issue by bas80836255** [go-redis/redismock#24]
my production code is
```
setArgs := redis.SetArgs{
  ExpireAt: time.UnixMilli(minTime),
  }
setCmd := c.redis.SetArgs(ctx, "counter_slug_pause_ssoid_day, "1", setArgs)
```
and in unit test is
```
clientMock.CustomMatch(func(expected, actual []interface{}) error {
		assert.Equal(t.T(), expected[0], actual[0])
		assert.Equal(t.T(), expected[1], actual[1])
		assert.Equal(t.T(), expected[2], actual[2])
		assert.Equal(t.T(), "paxt", actual[3])
		return nil
	}).ExpectSet("counter_slug_pause_ssoid_day, "1", 0).SetVal("ok")
```

when run found error
`parameters do not match, expectation '[set counter_slug_pause_ssoid_day 1]', but call to cmd '[set counter_slug_pause_ssoid_day 1 exat 0]'`

what is the best way to stub 'SetArgs' command

**Comment by agammell** [comment]
I've opened a PR to address this as I hit the same issue: https://github.com/go-redis/redismock/pull/34
