### ISSUE TITLE
Request go-redes v9 support

### ISSUE THREAD

**Issue by Jimmy01010** [go-redis/redismock#44]
Request go-redes v9 support, please~

**Comment by sejin-P** [comment]
Please

**Comment by dtsulik** [comment]
Opened PR #45

**Comment by monkey92t** [comment]
v9 will be finished within this week.

**Comment by dtsulik** [comment]
@sejin-P I have not, my PR is more of base for v9. It needs lot of work.

**Comment by sejin-P** [comment]
Although you couldn't have done all of features, you did a great job. Thank you for your efforts. @dtsulik

**Comment by monkey92t** [comment]
go-redis v9 is still in rc version, mock already supports go-redis 9.0.0-rc.2.
But we still need to wait for the official version of go-redis v9. 

Recently, I am considering compatibility with redis6 in the v9 version, it seems that it will take a while.

Sorry for neglecting mock-api some time ago...

**Comment by vmihailenco** [comment]
@monkey92t just heads up that the repo has been moved https://github.com/redis/go-redis. I will tag v9.0.0 in a few days some testing.

**Comment by monkey92t** [comment]
> @monkey92t just heads up that the repo has been moved https://github.com/redis/go-redis. I will tag v9.0.0 in a few days some testing.


😄I have updated the import of `redismock`

**Comment by monkey92t** [comment]
v9.0.1 releases
