### ISSUE TITLE
Expect for Module Loadex

### ISSUE THREAD

**Issue by SoulPancake** [go-redis/redismock#69]
https://github.com/redis/go-redis/pull/2490
We need to write mocks for this
And not sure what can we use from this package for that purpose
Can someone suggest on this?
Or do we need to build that as well?

**Comment by SoulPancake** [comment]
@monkey92t Can I raise a PR for ExpectModuleLoadex?

**Comment by monkey92t** [comment]
Sure~

**Comment by ktsivkov** [comment]
@monkey92t Does that mean, that in order to create a Pull Request for this project, we will first need to have the PR https://github.com/redis/go-redis/pull/2490 for redis merged?
