### ISSUE TITLE
Checking a hash set created with map is failing

### ISSUE THREAD

**Issue by 8tomat8** [go-redis/redismock#7]
In one of our applications, we are using `HSet`  to create a Redis hash map. We've been using the map syntax:
```go
cmd, err := redisCli.HSet("key", map[string]interface{}{"1": "one", "2": "two"})
```

The request is later unpacked into a slice of arguments (which is native for Redis). But as it was passed as a map, the order every time is different.
Then in the [mock.match](https://github.com/go-redis/redismock/blob/f956dbb642d1215270911af03938a01640a3798b/mock.go#L142-L179) function we iterate over the list of expected args and comparing it to the list of cmd args. This function accesses the elements by index, so chances of getting a match decrease with each new item added into the hash :smile: 

Workaround:
Use the slice syntax instead:
```go
cmd, err := redisCli.HSet("key", []string{"1", "one", "2", "two"})
```
It is more confusing but works :slightly_smiling_face: 

I'm not really sure what could be a good approach to handle this :confused: 
Possible solutions on my mind:
- Give the option to ignore an order of the argument pairs in tests. The same way as it is done with the `mock.MatchExpectationsInOrder(true)` option
- Add a check in the `match` function to ignore an order of the pairs if the called operation supports map syntax

**Comment by monkey92t** [comment]
sorry, i just saw your problem, i will fix it today.

**Comment by 8tomat8** [comment]
@monkey92t thanks a lot!
